# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 97da030f21592a59ab71a1f63665a85d10d03f71f8c432d6706e3307efe77817fab53cbb3292ddde3c8cc403900676915b4b7f49c1fe0017b348fc7fdf928e47

test:
  secret_key_base: 71bbc5714f5d4a2787cdd9f34acdb3fa0c7ff75d0b6f256f24f6df78b97d1b2fd67446758d819eb0a031556dd5842f2118bdb59c1105f94a16472fb0bb8396d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
